production:
    url: http://127.0.0.1:8180/fedora
development:
    url: http://127.0.0.1:8180/fedora
    user: 'fedoraAdmin'
    pass: 'fedora'
test: &TEST
    url: http://127.0.0.1:8180/fedora
cucumber:
    <<: *TEST
