production:
    url: http://127.0.0.1:8180/solr/development
development:
    url: http://127.0.0.1:8180/solr/development
test: &TEST
    url: http://127.0.0.1:8180/solr/development
cucumber:
    <<: *TEST
