production:
    url: http://localhost:8180/solr/production
development:
    url: http://openvault.wgbh.org/solr/production
test: &TEST
    url: http://localhost:8180/solr/production
cucumber:
    <<: *TEST
